#!/usr/bin/env php
<?php

const KIRBY_HELPER_DUMP = false;
const KIRBY_HELPER_E = false;

require __DIR__. '/bootstrap.php';

use App\Commands\Serve;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;

$container = new Container;
$events = new Dispatcher($container);

$artisan = new Application($container, $events, 'Version 1');
$artisan->setName('Kirby Console');

// Bind a command
$artisan->resolve(Serve::class);

$artisan->run();
