#!/usr/bin/env php
<?php

require __DIR__.'/util/vendor/autoload.php';

use Console\Commands\Serve;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;

$container = new Container;
$events = new Dispatcher($container);

$artisan = new Application($container, $events, 'Version 1');
$artisan->setName('Kirby Console');

// Bind a command
$artisan->resolve(Serve::class);

$artisan->run();
